# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8a54a99161ebdb26ce11cd2e5e2c7dcec46d1aa6356d13fd5e1b59c51eb637c7ae6c1db41909576c502cc93526440f6ecf4b21d37693e11b0ef0e833a329b6

test:
  secret_key_base: cf580f3ec76a5071c5b80f905cb9fc4b90188bd0a56b7f610da6a79856c2c8652961e303e8550a75bb01f5ff1ff05b10ad743173d3aec9de079fc316c6da18a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
